### ISSUE TITLE
Use libsecp256k1 v0.2.0?

### ISSUE THREAD

**Issue by kristapsk** [Simplexum/python-bitcointx#75] opened 2022-12-12 23:59 UTC
They have made release finally. https://github.com/bitcoin-core/secp256k1/releases/tag/v0.2.0

**Comment by whitslack** [comment] 2023-01-17 13:50
I get two unit test failures when using libsecp256k1 v0.2.0:

```
======================================================================
ERROR: test_tx_valid (bitcointx.tests.test_transactions.Test_CTransaction)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/python-bitcointx-1.1.3/work/python-bitcointx-python-bitcointx-v1.1.3/bitcointx/tests/test_transactions.py", line 296, in test_tx_valid
    VerifyScript(tx.vin[i].scriptSig, prevouts[tx.vin[i].prevout], tx, i, flags=flags)
  File "/var/tmp/portage/dev-python/python-bitcointx-1.1.3/work/python-bitcointx-python-bitcointx-v1.1.3/bitcointx/core/scripteval.py", line 1175, in VerifyScript
    raise VerifyScriptError("scriptPubKey returned false")
bitcointx.core.scripteval.VerifyScriptError: scriptPubKey returned false

======================================================================
FAIL: test_script (bitcointx.tests.test_scripteval.Test_EvalScript)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/python-bitcointx-1.1.3/work/python-bitcointx-python-bitcointx-v1.1.3/bitcointx/tests/test_scripteval.py", line 168, in test_script
    VerifyScript(scriptSig, scriptPubKey, txSpend, 0, flags, amount=nValue, witness=witness)
  File "/var/tmp/portage/dev-python/python-bitcointx-1.1.3/work/python-bitcointx-python-bitcointx-v1.1.3/bitcointx/core/scripteval.py", line 1175, in VerifyScript
    raise VerifyScriptError("scriptPubKey returned false")
bitcointx.core.scripteval.VerifyScriptError: scriptPubKey returned false

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/python-bitcointx-1.1.3/work/python-bitcointx-python-bitcointx-v1.1.3/bitcointx/tests/test_scripteval.py", line 171, in test_script
    self.fail('Script FAILED: %r %r %r with exception %r\n\nTest data: %r' % (scriptSig, scriptPubKey, comment, err, test_case))
AssertionError: Script FAILED: CBitcoinScript([x('304402200060558477337b9022e70534f1fea71a318caf836812465a2509931c5e7c4987022078ec32bd50ac9e03a349ba953dfd9fe1c8d2dd8bdb1d38ddca844d3d5c78c11801')]) CBitcoinScript([x('038282263212c609d9ea2a6e3e172de238d8c39cabd5ac1ca10646e23fd5f51508'), OP_CHECKSIG]) 'P2PK with too much R padding but no DERSIG' with exception VerifyScriptError('scriptPubKey returned false')

Test data: ['0x47 0x304402200060558477337b9022e70534f1fea71a318caf836812465a2509931c5e7c4987022078ec32bd50ac9e03a349ba953dfd9fe1c8d2dd8bdb1d38ddca844d3d5c78c11801', '0x21 0x038282263212c609d9ea2a6e3e172de238d8c39cabd5ac1ca10646e23fd5f51508 CHECKSIG', '', 'OK', 'P2PK with too much R padding but no DERSIG']
```

**Comment by whitslack** [comment] 2023-01-20 00:27
I too am unable to reproduce this failure on one my systems but can on the other. Both systems have the same version of Python and the same version of `libsecp256k1` compiled from identical sources, but the systems differ in their compiler version and compile flags. I am attempting to find the critical difference. This may actually be a libsecp256k1 bug.

**Comment by whitslack** [comment] 2023-01-20 03:07
It's not libsecp256k1. I can replace the `libsecp256k1.so.1.0.0` on my working system with the exact file from my non-working system, but the working system still works. Very strange! Now I'm wondering if maybe it's a difference in Glibc or maybe a difference in how Python was compiled.

**Comment by whitslack** [comment] 2023-01-20 04:07
@dgpv: What version of OpenSSL was your Python compiled against? My working system has 1.1.1s, and my non-working system has 3.0.7. I'll A/B test that difference when I get a chance.

**Comment by dgpv** [comment] 2023-01-20 11:47
1.1.1s

**Comment by dgpv** [comment] 2023-01-20 11:53
openssl is used only in `CPubKey.verify_nonstrict()`. It is used because `ecdsa_signature_parse_der_lax` is not compiled in libsecp by default. It might be that openssl 3.0.7 has some incompatibilities in the functions that are used inside `CPubKey.verify_nonstrict()`

**Comment by dgpv** [comment] 2023-07-28 21:05
current master uses libsecp256k1 v0.3.2

**Comment by kristapsk** [comment] 2023-09-16 13:43
> current master uses libsecp256k1 v0.3.2 in auto-tests

Probably worth updating to v0.4.0, which was released two weeks ago.

**Comment by dgpv** [comment] 2023-09-17 12:00
Updated to v0.4.0 in https://github.com/Simplexum/python-bitcointx/commit/b3fa71a94c0b5a7f14221e764fec87b62320858f
Tests pass: https://github.com/Simplexum/python-bitcointx/actions/runs/6213130828

**Comment by kristapsk** [comment] 2023-09-17 14:02
Updated also JoinMarket branch to v0.4.0. https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1515

**Comment by dgpv** [comment] 2023-12-09 11:54
new python-bitcointx release tests against libsecp256k1 0.4.0, closing this.

**Closed by dgpv** 2023-12-09 11:54 UTC
