### ISSUE TITLE
PSBT_Input.sign() can return None or PSBT_InpuSignInfo depending on input script type

### ISSUE THREAD

**Issue by AdamISZ** [Simplexum/python-bitcointx#39] opened 2020-08-07 20:04 UTC
In this line:

https://github.com/Simplexum/python-bitcointx/blob/master/bitcointx/core/psbt.py#L918

the library returns `None` if the input type is p2sh but no redeemscript is provided for this input. But as per https://github.com/Simplexum/python-bitcointx/commit/5d46995adf01733beba1b51da0e185da792e2208 , instead a PSBT_InputSignInfo with `is_final=False, num_new_sigs=0` is returned in cases where no key is found for signing.

This cropped up in testing of my SNICKER code in Joinmarket that queries a PSBT passed to the wallet that should have one signed (not owned by us) and one unsigned input, where we do a first check [here](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/7bf2ebb2cecbe9566b6416fca5d00c974067377b/jmclient/jmclient/wallet.py#L1473-L1478) that there is exactly one unsigned input (we earlier check there are exactly two inputs). We do this by passing an empty keystore to `PartiallySignedTransaction.sign()` [here](https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/7bf2ebb2cecbe9566b6416fca5d00c974067377b/jmclient/jmclient/wallet.py#L1434-L1442) (I believe i saw this in your codebase somewhere and copied the idea, memory a bit hazy).
(To be clear this SNICKER code is not yet at all used in action, it's still in a testing phase).

So overall, I am not sure whether this is intended behaviour, or a mistake, or something that could/should be changed.

**Comment by dgpv** [comment] 2020-08-08 06:05
This is intended behavior.

`None` is returned when there's no chance we could sign the input because something is incomplete in the information available from the PSBT, or cannot it be handled by the code, like a non-standard script (but no rules is breached, so no `ValueError`)

The "empty" `PSBT_InutSignInfo` is returned when everything is OK with PSBT, and we could sign it, but the key store does not contain the needed key.

I think that these are two different situations, and the caller should be able to distinguish them.

Maybe you can elaborate on what difficulty/problem you face because of this behavior of the library ? It is not clear to me after I skimmed through the code referenced. Is it possible that both incomplete input (without redeem script) and complete, but 'foreign' input, without the keys bear the same meaning in your protocol ?

**Comment by dgpv** [comment] 2020-08-08 06:30
> incomplete in the information available from the PSBT, or it cannot be handled by the code, like a non-standard script

Well here is another two different situations that the caller might be interested to distinguish (not provided vs not supported), but in both situations `None` is returned.

At the moment I am not sure if I should separate these two cases. I believe using `PSBT_InputSignInfo` for any of that cases is not appropriate, because the `num_sigs_missing` is not determined in this case.

**Comment by dgpv** [comment] 2020-08-08 06:37
Also, returning something other than `None` in the case when `None` was returned previously is quite a major breakage of the API, all the code that checked with `is None` will be wrong. The code that checked with `if info:` could be made to work by redefining `__bool__()` for the result class, but this would be quite ugly.

**Comment by dgpv** [comment] 2020-08-08 06:54
I think `PSBT_Input.sign()` could return None instead of empty `PSBT_InputSignInfo` in case when `keystore` is not supplied (will need to make `keystore` arg optional).

For distinguishing the "not supported script" / "missing info" cases, I believe an extra kwarg flag would be needed, to not break the `None`-returning API

**Comment by AdamISZ** [comment] 2020-08-08 10:13
> This is intended behavior.

Yes, I suspected as much and your explanation makes it clear. So, this is not really a problem, it's just that the "call sign() with empty keystore to inspect the signed-ness of the inputs" that I used in the above linked code, happens to get a different result returned for a p2sh case compared to a witness v0 case. It's easy for me to handle that, so I'll just do it.

(I doubt that adding more flags is needed just for this. And understood on API break.)

**Comment by dgpv** [comment] 2020-08-08 11:30
It is great that this behavior does not pose a problem.

This did reveal a small UX problem of the API, though (or should it be "DX" for "developer experience ? ;-))

I'll leave the issue open, because I think that the API can be improved by the changes that I described in my previous message, in a backwards-compatible way. I might return to this later with more thought.

**Comment by dgpv** [comment] 2020-10-17 14:37
> For distinguishing the "not supported script" / "missing info" cases, I believe an extra kwarg flag would be needed, to not break the None-returning API (those who need to distinguish, would supply this flag and handle results differently)

I don't think this is needed, because if someone wants to detect the case when an unsupported script is encountered, they can just supply their own `complex_script_helper_factory` (possibly just wrap `StandardMultisigSignatureHelper` to check the result and throw exception).

Closing the issue.

**Closed by dgpv** 2020-10-17 14:37 UTC
